# Generated by Django 4.2.16 on 2024-09-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='c_password',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
